In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

In [2]:
data = pd.read_csv('data/Simple linear regression.csv')
data.tail(3)

SAT   GPA
81  1987  3.73
82  1962  3.76
83  2050  3.81

In [3]:
x = data.SAT
y = data.GPA

In [4]:
x.shape, y.shape

((84,), (84,))

In [5]:
x_matrix = x.values.reshape(-1,1)
x_matrix.shape

(84, 1)

In [6]:
lr = LinearRegression()
lr.fit(x_matrix,y)

LinearRegression()

In [8]:
lr.intercept_, lr.coef_

(0.2750402996602803, array([0.00165569]))

In [9]:
newData = np.array(1790)
newData = newData.reshape(-1,1)

In [10]:
lr.predict(newData)

array([3.23872191])

In [11]:
data = pd.read_csv('data/Multiple linear regression.csv')
data.tail(3)

SAT   GPA  Rand 1,2,3
81  1987  3.73           3
82  1962  3.76           1
83  2050  3.81           2

In [12]:
x = data[['SAT','Rand 1,2,3']]
y = data.GPA

In [13]:
lr.fit(x, y)

LinearRegression()

In [14]:
lr.intercept_, lr.coef_

(0.29603261264909486, array([ 0.00165354, -0.00826982]))

In [17]:
lr.score(x,y)

0.40668119528142843

In [18]:
scaler = StandardScaler()
scaler.fit(x)

StandardScaler()

In [20]:
x_scaled = scaler.transform(x)
x_scaled[:5]

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087]])

In [21]:
lr.fit(x_scaled, y)
lr.intercept_, lr.coef_

(3.330238095238095, array([ 0.17181389, -0.00703007]))

In [31]:
lr.score(x_scaled, y)

0.4066811952814283

In [25]:
lr_summary = pd.DataFrame([['Base'],['SAT'],['Rand 1,2,3']], columns=['Feature'])
lr_summary

Feature
0        Base
1         SAT
2  Rand 1,2,3

In [26]:
lr_summary['weight'] = lr.intercept_, lr.coef_[0], lr.coef_[1]
lr_summary

Feature    weight
0        Base  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

In [27]:
new_data = pd.DataFrame({'SAT':[1700,1800],'Rand 1,2,3':[2,1]})

In [29]:
new_data_scaled = scaler.transform(new_data)

In [30]:
lr.predict(new_data_scaled)

array([3.09051403, 3.26413803])