## 1) Numpy Basic

In [1]:
import numpy as np

![](figures/array_vs_list.png)

In [3]:
import time

In [8]:
class Timer(object):
    def __init__(self, name = None):
        self.name = name
    def __enter__(self):
        self.tstart = time.time()
    def __exit__(self, type, value, traceback):
        if self.name:
            print('[%s]' %self.name)
        print('Elapsed : %s' %(time.time() - self.tstart))

In [9]:
with Timer('여기에 이름을 입력하세요'):
    time.sleep(1)

[여기에 이름을 입력하세요]
Elapsed : 1.0005028247833252


In [10]:
rows = 1000
cols = 1000
sampleRandom2DArray = np.random.rand(rows,cols)
sampleRandom2DList = sampleRandom2DArray.tolist()

In [11]:
with Timer('파이썬 리스트 - 모든 원소 합구하기'):
    sum = 0
    for ele in sampleRandom2DList:
        for e in ele:
            sum += e

[파이썬 리스트 - 모든 원소 합구하기]
Elapsed : 0.1037144660949707


In [13]:
with Timer('Numpy - 모든 원소 합구하기'):
    np.sum(sampleRandom2DArray)

[Numpy - 모든 원소 합구하기]
Elapsed : 0.004987239837646484


## 2) Numpy Creation

In [14]:
np.array([[1,2,3],[4,5,6]], np.int32)

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.array([1,2,3], np.float)

array([1., 2., 3.])

In [16]:
# np.ones(), np.full(), np.zeros()

In [17]:
np.ones((3,2), float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
np.full((4,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [19]:
np.zeros((5,2), int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [20]:
np.empty((1,4))

array([[5.e-324, 5.e-324, 0.e+000, 0.e+000]])

In [24]:
np.arange(4), np.arange(0,5,1), np.arange(1,10,2), np.arange(10,0,-2)

(array([0, 1, 2, 3]),
 array([0, 1, 2, 3, 4]),
 array([1, 3, 5, 7, 9]),
 array([10,  8,  6,  4,  2]))

In [26]:
np.linspace(0,1), np.linspace(0,1,10) # default 값은 50개

(array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
        0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
        0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
        0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
        0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
        0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
        0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
        0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
        0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
        0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ]),
 array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]))

In [28]:
x = np.ones([2,3,4])
x.shape

(2, 3, 4)

In [29]:
x.reshape(6,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
np.random.randint(0,10,(3,3))

array([[1, 8, 5],
       [0, 4, 9],
       [4, 5, 2]])

In [33]:
normArray = np.random.normal(0,1,(3,3))

In [34]:
np.mean(normArray), np.std(normArray)

(0.2901437259077507, 1.3386054828047869)

In [36]:
myArray = np.arange(1,10).reshape(3,3)
myArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
np.sum(myArray), np.sum(myArray, axis = 0), np.sum(myArray, axis = 1)

(45, array([12, 15, 18]), array([ 6, 15, 24]))

In [39]:
# max, min, mean, std, var, median
np.max(myArray), np.max(myArray, axis = 0), np.max(myArray, axis = 1)

(9, array([7, 8, 9]), array([3, 6, 9]))

In [42]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 3) Numpy Index, Slice

In [43]:
A = np.arange(1,13).reshape((3,4))
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
A[0][0],A[0][1]

(1, 2)

In [45]:
A[0,0], A[0,1],A[1,2]

(1, 2, 7)

In [46]:
A[:, :]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
A[[0,2], :]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [50]:
A[1:3,2:4]

array([[ 7,  8],
       [11, 12]])

In [52]:
B = np.random.randint(10, size = (3,4))
B

array([[7, 2, 5, 8],
       [0, 8, 4, 4],
       [8, 3, 7, 5]])

In [53]:
B[0,0] = 100
B

array([[100,   2,   5,   8],
       [  0,   8,   4,   4],
       [  8,   3,   7,   5]])

In [54]:
B[:2,:2] = 200
B

array([[200, 200,   5,   8],
       [200, 200,   4,   4],
       [  8,   3,   7,   5]])

In [55]:
x = np.array([1,2,3])
x.shape, x

((3,), array([1, 2, 3]))

In [57]:
x = x.reshape((1,3))
x.shape, x

((1, 3), array([[1, 2, 3]]))

In [58]:
# 축 하나 더 생성
x[np.newaxis,:]

array([[[1, 2, 3]]])

## 4) Universal Func

In [60]:
x = np.arange(4)
l = np.arange(4).tolist()
x, l

(array([0, 1, 2, 3]), [0, 1, 2, 3])

In [66]:
# 리스트타입 각 원소에 +5
[ele+5 for ele in l]

[5, 6, 7, 8]

In [67]:
# array타입 각 원소에 +5
x + 5

array([5, 6, 7, 8])

In [68]:
(x+5).tolist()

[5, 6, 7, 8]

In [69]:
y = -(1/2 * x + 1) ** 2

In [80]:
result = [x.tolist()]+[y.tolist()]
result = np.array(result).T
result

array([[ 0.  , -1.  ],
       [ 1.  , -2.25],
       [ 2.  , -4.  ],
       [ 3.  , -6.25]])

In [75]:
import pandas as pd

In [81]:
df = pd.DataFrame(result, columns = ['x','y'])
df

x     y
0  0.0 -1.00
1  1.0 -2.25
2  2.0 -4.00
3  3.0 -6.25

In [82]:
df.to_csv('test.csv')

In [83]:
theta = np.linspace(0,np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [84]:
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [85]:
x = np.arange(1,6)
np.add.reduce(x)

15

In [86]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [93]:
x = np.arange(1,20)
l = x.tolist()

In [88]:
[ele for ele in l if ele > 15]

[16, 17, 18, 19]

In [95]:
x[x > 15]

array([16, 17, 18, 19])

In [96]:
np.count_nonzero(x<5)

4